#!/bin/bash

RPL=/usr/bin/rpl
CP=/bin/cp
RM=/bin/rm
USERADD=/usr/sbin/useradd
USERDEL=/usr/sbin/userdel
OPENSSL=/usr/bin/openssl
CHOWN=/bin/chown
CHMOD=/bin/chmod
MKDIR=/bin/mkdir
LN=/bin/ln
CAT=/bin/cat
ECHO=/bin/echo
MKTEMP=/bin/mktemp
PWGEN=/usr/bin/pwgen
UPDATE_RC_D=/usr/sbin/update-rc.d

####################################################################################
SOFT_NAME=ehdtd-daemon
LIB_DIR=/usr/lib/${SOFT_NAME}
SYSTEMD_SERVICE=${SOFT_NAME}.service
SYSTEMD_PATH=${LIB_DIR}/systemd/${SYSTEMD_SERVICE}
VIRT_ENV_NAME="ehdtd-daemon-virtenv"
VIRT_ENV_PATH=${LIB_DIR}/${VIRT_ENV_NAME}
DEFAULT_FILE=/etc/default/${SOFT_NAME}
####################################################################################

if [ -f /usr/share/debconf/confmodule ]
then
    . /usr/share/debconf/confmodule
fi

if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
    . /usr/share/dbconfig-common/dpkg/postrm
    dbc_go ${SOFT_NAME} "$@"
fi

if [ "$1" = "purge" ]
then
    UCF="ucf"
    UCFR="ucfr"

    if command -v ucfq >/dev/null
    then
        for file in $(ucfq --with-colons "${SOFT_NAME}" | cut --delimiter=: --fields=1)
        do
            rm -f ${file}
            ucf --purge ${file}
            ucfr --purge ${SOFT_NAME} ${file}
        done
    else
        ${ECHO} >&2 "ucf no longer installed, not cleaning up"
    fi

    db_purge
    
    if which ucf >/dev/null 2>&1
    then
        ucf --purge /etc/${SOFT_NAME}/${SOFT_NAME}-config.yaml
    fi

    ${RM} -r -f ${LIB_DIR} 1>/dev/null 2>/dev/null
    ${RM} -r -f /etc/${SOFT_NAME} 1>/dev/null 2>/dev/null
    ${RM} -f ${DEFAULT_FILE} 1>/dev/null 2>/dev/null
fi







