#!/bin/bash

RPL=/usr/bin/rpl
CP=/bin/cp
RM=/bin/rm
USERADD=/usr/sbin/useradd
USERDEL=/usr/sbin/userdel
OPENSSL=/usr/bin/openssl
CHOWN=/bin/chown
CHMOD=/bin/chmod
MKDIR=/bin/mkdir
LN=/bin/ln
CAT=/bin/cat
ECHO=/bin/echo
MKTEMP=/bin/mktemp
PWGEN=/usr/bin/pwgen
BASENAME=/usr/bin/basename
UPDATE_RC_D=/usr/sbin/update-rc.d
SYSTEMCTL=/bin/systemctl

####################################################################################
SOFT_NAME=ehdtd-daemon
SYSTEMD_SERVICE=${SOFT_NAME}.service
####################################################################################

if [ "$1" = "upgrade" ]
then
  if [ -n "$2" ]
  then
    if [ -d /run/systemd/system ]
    then
        if ${SYSTEMCTL} is-enabled ${SYSTEMD_SERVICE} 1>/dev/null 2>/dev/null
        then
            ${SYSTEMCTL} stop ${SYSTEMD_SERVICE}
        fi
    fi
  fi
fi

