#!/bin/bash

RPL=/usr/bin/rpl
CP=/bin/cp
RM=/bin/rm
USERADD=/usr/sbin/useradd
USERDEL=/usr/sbin/userdel
OPENSSL=/usr/bin/openssl
CHOWN=/bin/chown
CHMOD=/bin/chmod
MKDIR=/bin/mkdir
LN=/bin/ln
CAT=/bin/cat
ECHO=/bin/echo
MKTEMP=/bin/mktemp
PWGEN=/usr/bin/pwgen
UPDATE_RC_D=/usr/sbin/update-rc.d
SYSTEMCTL=/bin/systemctl

####################################################################################
SOFT_NAME=__SOFT_NAME__
LIB_DIR=/usr/lib/${SOFT_NAME}
SYSTEMD_SERVICE=${SOFT_NAME}.service
SYSTEMD_PATH=${LIB_DIR}/systemd/${SYSTEMD_SERVICE}
VIRT_ENV_NAME="ehdtd-daemon-virtenv"
VIRT_ENV_PATH=${LIB_DIR}/${VIRT_ENV_NAME}
####################################################################################

if [ -f /usr/share/debconf/confmodule ]
then
    . /usr/share/debconf/confmodule
fi

if [ "$1" = "remove" ]
then
    if ${SYSTEMCTL} is-enabled ${SYSTEMD_SERVICE} 1>/dev/null 2>/dev/null
    then
        ${SYSTEMCTL} stop ${SYSTEMD_SERVICE}
        ${SYSTEMCTL} disable ${SYSTEMD_SERVICE}
    fi
    
    if [ -f /usr/share/dbconfig-common/dpkg/prerm ]
    then
        . /usr/share/dbconfig-common/dpkg/prerm
        dbc_go ${SOFT_NAME} $@
    fi
fi


